name: StatPull
on: 
    workflow_dispatch:
    #schedule:
        #- cron: '0 11 * * *' # Runs every day at 11:00 AM UTC (7:00 AM EST)

jobs:
    build:
      name: Run Script
      runs-on: windows-latest
      steps:
        - uses: actions/checkout@v1
        - name: Install PowerHTML module
          shell: pwsh
          run: Install-Module -Name PowerHTML -Force
        - name: Script
          run: .\Get-Stats.ps1
            $commitMsg = "[$(get-date -Format 'yyyy.MM.dd:hh.mm.ss')]Updated stats for 2025"
            git config user.name github-actions[bot]
            git config user.email github-actions[bot]@users.noreply.github.com
            git add 2025.csv
            git commit -m $commitMsg
          shell: pwsh
        - name: Push changes # push the output folder to your repo
          uses: ad-m/github-push-action@master
          with:
            github_token: ${{ secrets.GITHUB_TOKEN  }}
            force: true
          

